p8105_hw2_hj2735
================
cindyjin
2025-09-30

### Problem 1

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   3.5.2     ✔ tibble    3.3.0
    ## ✔ lubridate 1.9.4     ✔ tidyr     1.3.1
    ## ✔ purrr     1.1.0     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
# Load CSV from the data/ subdirectory
pols_month = read_csv("data/fivethirtyeight_datasets/pols-month.csv")
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
unemployment = read_csv("data/fivethirtyeight_datasets/unemployment.csv")
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
snp = read_csv("data/fivethirtyeight_datasets/snp.csv")
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
pols_month = pols_month |>
  separate(mon, into = c("year", "month", "day"), sep = "-", convert = TRUE) |>
  mutate(
    month     = factor(month.name[month], levels = month.name),   # replace number with month name
    president = if_else(prez_gop == 1, "gop", "dem")              # create president variable
  ) |>
  select(year, month, everything(), -prez_dem, -prez_gop, -day) |>  # remove prez_dem, prez_gop, day
  arrange(year, month)

# Preview cleaned data
glimpse(pols_month)
```

    ## Rows: 822
    ## Columns: 9
    ## $ year      <int> 1947, 1947, 1947, 1947, 1947, 1947, 1947, 1947, 1947, 1947, …
    ## $ month     <fct> January, February, March, April, May, June, July, August, Se…
    ## $ gov_gop   <dbl> 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 24, 24, 22, 22, 22, …
    ## $ sen_gop   <dbl> 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 53, 53, 53, …
    ## $ rep_gop   <dbl> 253, 253, 253, 253, 253, 253, 253, 253, 253, 253, 253, 253, …
    ## $ gov_dem   <dbl> 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 24, 24, 24, …
    ## $ sen_dem   <dbl> 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 48, 48, 48, …
    ## $ rep_dem   <dbl> 198, 198, 198, 198, 198, 198, 198, 198, 198, 198, 198, 198, …
    ## $ president <chr> "dem", "dem", "dem", "dem", "dem", "dem", "dem", "dem", "dem…

``` r
head(pols_month)
```

    ## # A tibble: 6 × 9
    ##    year month    gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president
    ##   <int> <fct>      <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>    
    ## 1  1947 January       23      51     253      23      45     198 dem      
    ## 2  1947 February      23      51     253      23      45     198 dem      
    ## 3  1947 March         23      51     253      23      45     198 dem      
    ## 4  1947 April         23      51     253      23      45     198 dem      
    ## 5  1947 May           23      51     253      23      45     198 dem      
    ## 6  1947 June          23      51     253      23      45     198 dem

``` r
# Clean snp data
snp = snp |>
  separate(date, into = c("month", "day", "year"), sep = "/", convert = TRUE) |>
  mutate(
    # Convert 2-digit year to 4-digit year
    year = if_else(year < 50, year + 2000, year + 1900),
    month = factor(month.name[month], levels = month.name)
  ) |>
  select(year, month, everything(), -day) |>
  arrange(year, month)

# Preview cleaned data
glimpse(snp)
```

    ## Rows: 787
    ## Columns: 3
    ## $ year  <dbl> 1950, 1950, 1950, 1950, 1950, 1950, 1950, 1950, 1950, 1950, 1950…
    ## $ month <fct> January, February, March, April, May, June, July, August, Septem…
    ## $ close <dbl> 17.05, 17.22, 17.29, 17.96, 18.78, 17.69, 17.84, 18.42, 19.45, 1…

``` r
head(snp)
```

    ## # A tibble: 6 × 3
    ##    year month    close
    ##   <dbl> <fct>    <dbl>
    ## 1  1950 January   17.0
    ## 2  1950 February  17.2
    ## 3  1950 March     17.3
    ## 4  1950 April     18.0
    ## 5  1950 May       18.8
    ## 6  1950 June      17.7

``` r
unemployment = unemployment |>
  pivot_longer(
    cols = -Year,
    names_to = "month",
    values_to = "unemployment"
  ) |>
  mutate(
    year  = Year,
    # standardize month abbreviations to full names
    month = recode(month,
                   Jan = "January", Feb = "February", Mar = "March",
                   Apr = "April",   May = "May",      Jun = "June",
                   Jul = "July",    Aug = "August",   Sep = "September",
                   Oct = "October", Nov = "November", Dec = "December"),
    month = factor(month, levels = month.name),
    unemployment = as.numeric(unemployment)
  ) |>
  select(year, month, unemployment) |>
  arrange(year, month)

# Preview cleaned unemployment data
glimpse(unemployment)
```

    ## Rows: 816
    ## Columns: 3
    ## $ year         <dbl> 1948, 1948, 1948, 1948, 1948, 1948, 1948, 1948, 1948, 194…
    ## $ month        <fct> January, February, March, April, May, June, July, August,…
    ## $ unemployment <dbl> 3.4, 3.8, 4.0, 3.9, 3.5, 3.6, 3.6, 3.9, 3.8, 3.7, 3.8, 4.…

``` r
head(unemployment)
```

    ## # A tibble: 6 × 3
    ##    year month    unemployment
    ##   <dbl> <fct>           <dbl>
    ## 1  1948 January           3.4
    ## 2  1948 February          3.8
    ## 3  1948 March             4  
    ## 4  1948 April             3.9
    ## 5  1948 May               3.5
    ## 6  1948 June              3.6

``` r
merged = pols_month |>
  left_join(snp, by = c("year", "month")) |>
  left_join(unemployment, by = c("year", "month"))

# Quick summary
dim(merged)
```

    ## [1] 822  11

``` r
range(merged$year)
```

    ## [1] 1947 2015

``` r
names(merged)
```

    ##  [1] "year"         "month"        "gov_gop"      "sen_gop"      "rep_gop"     
    ##  [6] "gov_dem"      "sen_dem"      "rep_dem"      "president"    "close"       
    ## [11] "unemployment"

The **`pols_month`** dataset provides monthly data, including the number
of national politicians by party affiliation and an indicator of the
president’s party (Democrat or Republican). The **`snp`** dataset
records closing values of the S&P stock index on a monthly basis, giving
a financial measure of U.S. market performance. The **`unemployment`**
dataset contains monthly unemployment rates across the U.S. economy.

After cleaning and merging these three sources, the resulting dataset
contains information on **politics, markets, and the economy** in one
place. The merged data frame has 822 rows and 11 columns, covering the
years from 1947 through 2015. Key variables include `year`, `month`,
`president`, `close` (S&P closing price), and `unemployment`. This
unified dataset allows for examining relationships between political
events, stock market fluctuations, and unemployment trends across
decades.

``` r
# save the merged result for reference
write_csv(merged, "data/merged_pols_snp_unemployment.csv")
```

### Problem 2

``` r
library(readxl)
library(janitor)
```

    ## 
    ## Attaching package: 'janitor'

    ## The following objects are masked from 'package:stats':
    ## 
    ##     chisq.test, fisher.test

``` r
trash_path = "data/202509 Trash Wheel Collection Data.xlsx" 
```

``` r
read_trash <- function(sheet_name, wheel_label) {
  read_excel(trash_path, sheet = sheet_name, skip = 1) |>
    clean_names() |>
    # keep only dumpster-specific rows (omit notes / figures)
    filter(!is.na(dumpster)) |>
    # standardize types and add identifier
    mutate(
      month = as.character(month),
      year  = as.integer(year),
      trash_wheel = wheel_label
    ) |>
    # round sports_balls to int if the column exists on that sheet
    mutate(across(any_of("sports_balls"), ~ as.integer(round(.x)))) |>
    # drop any columns that are entirely NA (leftover “notes” columns after clean_names)
    select(where(~ !all(is.na(.x))))
}

mr   <- read_trash("Mr. Trash Wheel", "Mr. Trash Wheel")
```

    ## New names:
    ## • `` -> `...15`
    ## • `` -> `...16`

``` r
prof <- read_trash("Professor Trash Wheel", "Professor Trash Wheel")
gwyn <- read_trash("Gwynns Falls Trash Wheel", "Gwynnda")

# combine all three into one tidy dataset
trash_all <- bind_rows(mr, prof, gwyn)
```

``` r
n_obs   <- nrow(trash_all)
n_vars  <- ncol(trash_all)
year_lo <- min(trash_all$year, na.rm = TRUE)
year_hi <- max(trash_all$year, na.rm = TRUE)

# summaries
prof_total_weight <- prof |>
  summarise(total_weight_tons = sum(weight_tons, na.rm = TRUE)) |>
  pull(total_weight_tons)

gwyn_june22_cigs <- gwyn |>
  filter(year == 2022, month == "June") |>
  summarise(total_cigs = sum(cigarette_butts, na.rm = TRUE)) |>
  pull(total_cigs)
```

The **`Mr. Trash Wheel`** dataset provides per-dumpster collection
records (by month and year), including weight and volume of trash
removed and counts of common debris (e.g., plastic bottles, polystyrene,
cigarette butts). The **`Professor Trash Wheel`** dataset contains the
same types of measures for a different installation, recorded with the
same structure. The **`Gwynnda (Gwynns Falls Trash Wheel)`** dataset
likewise reports per-dumpster totals for weight, volume, and itemized
debris counts.

After cleaning and combining these three sources, the resulting dataset
contains information on **trash removal activity across multiple Trash
Wheels** in one place. The merged data frame has **1188** rows and
**15** columns, covering the years from **2014** through **2025**. Key
variables include `trash_wheel` (source identifier), `dumpster`,
`month`, `year`, `date`, `weight_tons`, `volume_cubic_yards`,
`plastic_bottles`, `polystyrene`, `cigarette_butts`, `glass_bottles`,
`plastic_bags`, `wrappers`, `sports_balls` (where available), and
`homes_powered`.

``` r
# save merged
write_csv(trash_all, "data/merged_trash_wheels.csv")
```

### Problem 3

``` r
library(lubridate)
library(stringr)
zip_codes = read_csv("data/zillow_data/Zip Codes.csv")
```

    ## Rows: 322 Columns: 7
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (4): County, County Code, File Date, Neighborhood
    ## dbl (3): State FIPS, County FIPS, ZipCode
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
zori = read_csv("data/zillow_data/Zip_zori_uc_sfrcondomfr_sm_month_NYC.csv")
```

    ## Rows: 149 Columns: 125
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr   (6): RegionType, StateName, State, City, Metro, CountyName
    ## dbl (119): RegionID, SizeRank, RegionName, 2015-01-31, 2015-02-28, 2015-03-3...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
zip_codes = zip_codes |> clean_names()
zori = zori |> clean_names()
```

``` r
# County -> Borough map
county_to_borough = c(
  "Bronx"    = "Bronx",
  "Kings"    = "Brooklyn",
  "New York" = "Manhattan",
  "Queens"   = "Queens",
  "Richmond" = "Staten Island"
)

zip_tbl = zip_codes |>
  transmute(
    zip          = str_pad(as.character(zip_code), width = 5, pad = "0"),
    county       = county,
    borough      = recode(county, !!!county_to_borough),
    neighborhood = neighborhood
  ) |>
  mutate(
    neighborhood = str_squish(neighborhood),   # trim + collapse multiple spaces
    neighborhood = na_if(neighborhood, "")     # turn blanks into NA
  ) |>
  distinct() |>
  arrange(borough, neighborhood, zip)
```

``` r
# Detect monthly columns whether they look like "2015-01-31" or "x2015_01_31"
date_cols = names(zori) |> keep(~ str_detect(.x, "^\\d{4}-\\d{2}-\\d{2}$"))
if (length(date_cols) == 0) {
  date_cols = names(zori) |> keep(~ str_detect(.x, "^(x)?\\d{4}[_-]\\d{2}[_-]\\d{2}$"))
}
stopifnot(length(date_cols) > 0)

name_to_date = function(s) {
  s |>
    str_remove("^x") |>          # drop leading 'x' if present
    str_replace_all("_", "-") |> 
    ymd(quiet = TRUE)
}

zori_long = zori |>
  pivot_longer(
    cols      = all_of(date_cols),
    names_to  = "date_name",
    values_to = "zori"
  ) |>
  mutate(
    zip   = str_pad(as.character(region_name), width = 5, pad = "0"),
    date  = name_to_date(date_name),
    year  = year(date),
    month = month(date)
  ) |>
  select(zip, city, state_name, date, year, month, zori) |>
  arrange(zip, date)
```

``` r
zip_tbl_uni = zip_tbl |>
  group_by(zip) |>
  summarise(
    borough      = dplyr::first(na.omit(borough)),
    county       = dplyr::first(na.omit(county)),
    neighborhood = paste(sort(unique(na.omit(neighborhood))), collapse = "; "),
    .groups = "drop"
)

# then join with zip_tbl_uni instead of zip_tbl
nyc_tidy = zori_long |>
  left_join(zip_tbl_uni, by = "zip") |>
  relocate(zip, borough, county, neighborhood, city, state_name,
           date, year, month, zori) |>
  arrange(borough, neighborhood, zip, date)

write_csv(nyc_tidy, "data/nyc_zori_zip_tidy.csv")
```

``` r
# ZIPs present in the ZIP file but NOT in Zillow
zips_in_zipfile = unique(zip_tbl$zip)
zips_in_zillow  = str_pad(as.character(zori$region_name), 5, pad = "0")
zips_missing_vec = setdiff(zips_in_zipfile, zips_in_zillow)

zips_missing_tbl = tibble(zip = zips_missing_vec) |>
  left_join(zip_tbl, by = "zip") |>
  arrange(borough, neighborhood, zip)

write_csv(zips_missing_tbl, "data/zips_missing_in_zillow.csv")

# small sample for inline text
examples_missing = zips_missing_tbl |> slice_head(n = 15)
```

``` r
# Compare Jan 2021 vs Jan 2020 (only where both exist)
jan_2020 = nyc_tidy |>
  filter(date == as.Date("2020-01-31")) |>
  select(zip, zori_2020_01 = zori)

jan_2021 = nyc_tidy |>
  filter(date == as.Date("2021-01-31")) |>
  select(zip, zori_2021_01 = zori)

delta_2021_vs_2020 = jan_2020 |>
  inner_join(jan_2021, by = "zip") |>
  mutate(change_2021_minus_2020 = zori_2021_01 - zori_2020_01) |>
  left_join(select(zip_tbl, zip, borough, neighborhood), by = "zip") |>
  relocate(zip, borough, neighborhood, zori_2020_01, zori_2021_01, change_2021_minus_2020)

top10_drop = delta_2021_vs_2020 |>
  arrange(change_2021_minus_2020) |>
  slice_head(n = 10) |>
  mutate(
    Jan_2020 = round(zori_2020_01),
    Jan_2021 = round(zori_2021_01),
    Change_2021_minus_2020 = round(change_2021_minus_2020)
  ) |>
  select(zip, borough, neighborhood, Jan_2020, Jan_2021, Change_2021_minus_2020)

write_csv(top10_drop, "data/nyc_top10_drop_2020_to_2021.csv")

top10_drop
```

    ## # A tibble: 10 × 6
    ##    zip   borough   neighborhood         Jan_2020 Jan_2021 Change_2021_minus_2020
    ##    <chr> <chr>     <chr>                   <dbl>    <dbl>                  <dbl>
    ##  1 10007 Manhattan Lower Manhattan          6334     5422                   -913
    ##  2 10069 Manhattan <NA>                     4623     3875                   -748
    ##  3 10009 Manhattan Lower East Side          3406     2692                   -714
    ##  4 10016 Manhattan Gramercy Park and M…     3731     3019                   -712
    ##  5 10001 Manhattan Chelsea and Clinton      4108     3398                   -710
    ##  6 10002 Manhattan Lower East Side          3645     2935                   -710
    ##  7 10004 Manhattan Lower Manhattan          3150     2444                   -706
    ##  8 10038 Manhattan Lower Manhattan          3573     2876                   -698
    ##  9 10012 Manhattan Greenwich Village a…     3629     2942                   -686
    ## 10 10010 Manhattan Gramercy Park and M…     3697     3012                   -685

``` r
# counts for write-up
n_obs  = nrow(nyc_tidy)
n_zip  = n_distinct(nyc_tidy$zip)
# ignore empty strings for neighborhood counts
n_nbhd = nyc_tidy |>
  filter(neighborhood != "", neighborhood != " ") |>
  distinct(neighborhood) |>
  nrow()
```

The **ZIP code dataset** lists NYC ZIPs and their associated **county
(borough) and neighborhood** names; this provides the geographic bridge
to attach borough/neighborhood context to rental prices. The **Zillow
ZORI dataset** provides **monthly rental price indices** by ZIP.

After importing, cleaning, and merging, the resulting tidy dataset
contains **17284** observations (each row is **ZIP × month**), with
**149** unique ZIP codes and **42** unique neighborhoods. Key variables
include `zip`, `borough`, `neighborhood`, `date` (plus `year`, `month`),
and `zori` (Zillow Observed Rent Index).

There are **171** ZIP codes in the ZIP file that do not appear in Zillow
(saved to file). Examples include **10474, 10475, 10464, 10499, 10550,
10704, 10705, 10803, 11239, 11224, 11202, 11241, 11242, 11243, 11245**.
These are commonly **special-use or non-residential** ZIPs (e.g., PO
boxes, single-building/commercial ZIPs) or areas with **insufficient
rental inventory**, so Zillow omits them.

To assess pandemic-era changes, we compared **January 2021 vs January
2020** ZORI for ZIPs with both months available and list the **10
largest drops** in the table above. Declines cluster in core
neighborhoods (notably in Manhattan), consistent with early-pandemic
rental dynamics.
